[package]
name = "pigeonrs_core"
version = "0.1.0"
authors = ["Michael Christenson II <michael@datagrail.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
